### PR TITLE
Fix STM32H72x/73x memory map

### LINKED ISSUE #64: Memory data wrong for some H7
The memory map data in the device file generator is wrong for some H7 devices.

Datasheet H723ZG:
h723_sram

Device file:
```
<memory name="itcm" access="rwx" start="0x00" size="65536"/>
<memory device-size="e" name="flash" access="rx" start="0x8000000" size="524288"/>
<memory device-size="g" name="flash" access="rx" start="0x8000000" size="1048576"/>
<memory name="dtcm" access="rwx" start="0x20000000" size="131072"/>
<memory name="d1_sram" access="rwx" start="0x24000000" size="524288"/>
<memory name="d2_sram1" access="rwx" start="0x30000000" size="131072"/>
<memory name="d2_sram2" access="rwx" start="0x30020000" size="131072"/>
<memory name="d2_sram3" access="rwx" start="0x30040000" size="32768"/>
<memory name="d3_sram" access="rwx" start="0x38000000" size="65536"/>
<memory name="backup" access="rwx" start="0x38800000" size="4096"/>
```

The data sheet has max. 320 kB AXI SRAM but the device file says 524288. Also our device files probably can't model the memory that is remappable between ITCM and AXI SRAM.

### PR DESCRIPTION
**Pull request by chris-durand**
Fixes #64. The H7 controllers with 564 kB of RAM incorrectly have 1024 kB in the devices files. The default setting of 64 kB ITCM / 320kB AXI SRAM is assumed for the remappable memory.

From the reference manual:
h723_sram

### CODE REVIEW

**Comment by salkinium** [comment]
So the mapping is configured via the Option Bytes, which is not at all considered in our device files. In this case the linkerscript will have to be adapted via an lbuild option, however, it's also easy to adapt the linkerscript yourself and replace the modm one via the `modm:platform:cortex-m:linkerscript.override` option, so I don't think we should deal with this now.



Also funny: "Refer to Section 4: Embedded Flash memory (FLASH) for a description of the TCM_AXI_SHARED option byte."
There is no description.



I'm doing a couple more spot checks on RAM sizes. Really annoying to dig through all the Datasheets separately. Kinda wish there was a single "Overview Datasheet".

**Comment by chris-durand** [comment]
> I'm doing a couple more spot checks on RAM sizes. Really annoying to dig through all the Datasheets separately. Kinda wish there was a single "Overview Datasheet".

Luckily for H7 the RAM sizes seem to be completely independent from package or flash sizes and are the same for a particular device. That's at least what CubeMX shows ...

**Comment by salkinium** [comment]
> That's at least what CubeMX shows ...

But CubeMX only shows the sum of all RAM right? Otherwise we could extract the mapping directly?

**Comment by chris-durand** [comment]
> But CubeMX only shows the sum of all RAM right? Otherwise we could extract the mapping directly?

Sadly, yes.

**Comment by salkinium** [comment]
Yup, it all checked out.

**Pull request merged**
