### PR TITLE
Allow the curated part of modm_devices to be built as a python package.

### PR DESCRIPTION
**Pull request by tgree**

### CODE REVIEW

**Comment by tgree** [comment]
Hi @salkinium!   I've created a pull request here that allows the curated part of the modm-devices repo to be packaged up in a way suitable for making it a pip package.  It includes the generated XML files directly in the pip package; a potential user could then simply 'pip3 install modm-devices' (assuming a pypi.org package was created) and get the latest XML.  As new XML is updated over time, the pypi.org package could be updated and then end-users would be able to easily consume this stuff.

Also, by making it a package like this dependency management becomes a lot easier.  For me, I'd like to use this in my stm_layout project.  I'd like to distribute stm_layout as a pypi.org project and specify a dependency on modm-devices to just get pip to install everything automatically.

I hope this is something you might be interested in!

**Comment by salkinium** [comment]
> I hope this is something you might be interested in!

Absolutely! The long term goal is to not only package the raw data, but also a Python API that provides access to implied and derived data as well, and perhaps useful modifier algorithms on top of that. PyPi is definitely the first step towards that goal.

I'll push some commit on top of this PR to add automated deploy via Travis.

**Comment by salkinium** [comment]
So now there's this: https://pypi.org/project/modm-devices/

This unblocks you, however make sure to depend on 0.1.0, because I'm not yet sure how to version data bug fixes correctly (data is semantic? Maybe?). However I will have to restructure the modm_devices folder a little to make it useful as a stand-alone package, so a proper integration will have to wait a short while, until I have some free mental time.

**Comment by tgree** [comment]
That's awesome, I'm glad to see this happening!  I guess the other thing I would need is for the pin location information to also get merged in to the repository (i.e. PA1 is on pin "9" for the STM32G474CET but is on pin "G2" [BGA pin names] for the STM32G474VBH, etc.).  I can clean up my branch and submit a second pull request if you would consider taking that change as well.

**Comment by salkinium** [comment]
Sure, but make the gpio-pin mapping a separate list in the gpio driver, otherwise it'll duplicate entire gpio nodes!

**Comment by salkinium** [comment]
I'm closing this in favor of #41, which automates the publishing via Travis.

**Pull request closed without merging**
