### PR TITLE
[dfg] Remap STM32F7 Flash to ITCM bus

### PR DESCRIPTION
**Pull request by salkinium**
As a followup to #54.

I've tried different configurations, but this is the simplest and requires no changes to any linkerscript. I've tested this on the STM32F746 Discovery examples.

cc @mikewolfram

### CODE REVIEW

**Comment by tgree** [comment]
Hey @salkinium,

I was just browsing your commits and noticed this one where you remapped the H7 flash to 0x00200000.  I have an H7-based sensor and was interested in this but after scouring RM0399 I couldn't find any mention of this alternate address.  I see it does show up in the F7 manuals - did you find an H7 reference somewhere for this as well, or were you able to test it on a real device?  I'll try it later today to see if it works but I'd be interested to see an ST reference for this.

**Comment by salkinium** [comment]
It's complicated: the access goes through different busses depending on Address, we want to use the ITCM access:
https://github.com/modm-io/modm-devices/pull/54#issuecomment-700932343

**Comment by salkinium** [comment]
Ah, but maybe I didn't pay attention for the H7, it's definitely only tested on the F7, since H7 support is still missing in modm (even though I have the hardware).

**Comment by salkinium** [comment]
Yeah, skimming through the H7 RMs, the modm-devices data is definitely just wrong for the H7. It needs to be fixed.

**Pull request merged**
