### PR TITLE
Add STM32L5 devices

### PR DESCRIPTION
**Pull request by chris-durand**

### CODE REVIEW

**Review by salkinium — APPROVED** [review]
Surprisingly few changes for a new family…

**Comment by chris-durand** [comment]
> Surprisingly few changes for a new family…

Very few in the device files but I have already included the changes for the L5 DMA data in the DMA data PR.

ST nevertheless missed no opportunity to introduce more confusing naming. For example, on L5 the core voltage settings are called `Range 0` to `Range 2` starting from 0, on L4 they start from 1, H7 has `Scale 0` to `Scale 3`, on G4 there is also `Range 1` and `Range 2` but no `Range 0` which is called `R1MODE` instead ...

**Comment by chris-durand** [comment]
@salkinium Merge or should we increase the version?

**Review by salkinium — APPROVED** [review]
Yes let's bump the version to 0.6.0.

**Comment by salkinium** [comment]
Nvm I can do that too.

**Pull request merged**
