### PR TITLE
Add support for SAMV devices

### PR DESCRIPTION
**Pull request by twasilczyk**

### CODE REVIEW

**Comment by salkinium** [comment]
How compatible are the peripherals to the SAMD or SAMG series? Currently all driver types are all `"sam"`, which could perhaps cause confusion with SAMD. (Perhaps we should rename those to `"samd"` too?)

**Comment by twasilczyk** [comment]
AFAIK SAMV70 is just an automotive equivalent of SAME70. I'm afraid I'll have no idea about SAMD/SAMG peripheral compatibility before I'll make it work.

**Comment by salkinium** [comment]
Ok, then lets change it all to samv, then we can later still unify those drivers that share something.

**Comment by mcbridejc** [comment]
> How compatible are the peripherals to the SAMD or SAMG series? Currently all driver types are all `"sam"`, which could perhaps cause confusion with SAMD. (Perhaps we should rename those to `"samd"` too?)

Looking over the SAMV datasheet now, I'd say it's closer to SAMG than it is to the SAMD series, but different. Seems to have the same GPIO and PMC/clock setup as SAMG (which is different from SAMD), but it does not have the flexcom combined SPI/UART/I2C peripherals.

When I first looked at this, I decided to let the "sam" types alone, wanting to minimize impact on existing code. But now that I've gotten more into it, it seems like there's not actually too much samd support yet, and maybe now's a good time to go ahead and be more specific; i.e. "sam" -> "samd".

**Comment by mcbridejc** [comment]
> How compatible are the peripherals to the SAMD or SAMG series? Currently all driver types are all `"sam"`, which could perhaps cause confusion with SAMD. (Perhaps we should rename those to `"samd"` too?)

Looking over the SAMV datasheet now, I'd say it's closer to SAMG than it is to the SAMD series, but different. Seems to have the same GPIO and PMC/clock setup as SAMG (which is different from SAMD), but it does not have the flexcom combined SPI/UART/I2C peripherals.

When I first looked at this, I decided to let the "sam" types alone, wanting to minimize impact on existing code. But now that I've gotten more into it, it seems like there's not actually too much samd support yet, and maybe now's a good time to go ahead and be more specific; i.e. "sam" -> "samd".

**Review by salkinium — APPROVED** [review]
We'll refactor "sam" to "samd" at a later time.

**Comment by twasilczyk** [comment]
Isn’t this supposed to go in before the change in core modm?

**Comment by salkinium** [comment]
Yes, just forgot about it, while battling the CI.

**Pull request merged**
