### PR TITLE
Add I2C support for whole STM32 family

### PR DESCRIPTION
**Pull request by strongly-typed**
Prerequisite to work on modm-io/modm#101

### CODE REVIEW

**Comment by chris-durand** [comment]
I also just wanted to open a pull request :wink: (https://github.com/chris-durand/modm-devices/tree/feature/stm32_extended_i2c). I worked through all reference manuals to correctly model the different feature sets of the I2C instances.

**Comment by strongly-typed** [comment]
@chris-durand Yours seems to be more elaborated than mine. I'll add your changes and will give credit.

**Comment by chris-durand** [comment]
@strongly-typed Would it be ok for you to close this PR and let me open one with the more comprehensive data from [here](https://github.com/chris-durand/modm-devices/commit/734cb9224a6fe8d7ea0f8f62a7bf71bdd47245c6)?
I am also doing some work on the extended i2c driver right now and would probably open another conflicting pull request tonight.

**Comment by strongly-typed** [comment]
@chris-durand takes over

**Comment by chris-durand** [comment]
Thanks

**Pull request closed without merging**
