### PR TITLE
Fix STM32G4 SRAM sizes

### PR DESCRIPTION
**Pull request by twast92**
See #85 for full context.

At the time of writing, this PR addresses the first problem mentioned in #85 (incorrect \<Ram\> section for g4{91|a1) devices) and the misplaced g471 series devices.

I still have a strong feeling that there is another issue in the way the SRAM1 size is calculated (see the 2nd problem in the linked issue)

### CODE REVIEW

**Comment by salkinium** [comment]
> I still have a strong feeling that there is another issue in the way the SRAM1 size is calculated

Maybe? Are there significant differences in the memory map between G491/G4A1 and the other G4 devices that point to an issue with the subtraction algorithm?

**Comment by salkinium** [comment]
Looking at the generated file, the merging filters may become a little calmer if the G471 was put into its own group here:
https://github.com/modm-io/modm-devices/blob/develop/tools/generator/dfg/stm32/stm_groups.py#L214

**Comment by chris-durand** [comment]
> Maybe? Are there significant differences in the memory map between G491/G4A1 and the other G4 devices that point to an issue with the subtraction algorithm?

```
<memory device-name="91|a1" name="sram1" access="rwx" start="0x20000000" size="98304"/>
<memory device-name="91|a1" name="sram2" access="rwx" start="0x20018000" size="16384"/>
```

SRAM1 is still to big in the generated file. Thus, the start address of SRAM2 is off, too. The reason could be that ST included the CCM in the RAM size value in the device data. In G4 devices the CCM is not only mapped at `0x10000000` but also at the end of SRAM2. That could explain why they count it as a part of the standard SRAM as well.

sram

**Comment by twast92** [comment]
Yes, exactly what you wrote @chris-durand!
The only reason this has not been a problem is due to the CCM SRAM being mapped in continuity of SRAM2.

And this problem is present for all G4 devices, not just the 491 series.
I only happened to notice because ST specified the wrong Ram size in their cubemx data, leading to a weird crash when flashing with RTT enabled... fun! :D

**Comment by twast92** [comment]
I haven't spent too much time looking at the linkerscript, but I'd imagine this also means the CCM SRAM is technically able to be inadvertently modified if someone really pushes the SRAM1+2 space

**Comment by twast92** [comment]
I had a bit of time to work on this, so here's a possible solution.
I've tested it with the stm32g491met6 board I've been working with and everything seems to still be working as expected.

I'm not particularly proud of the way I handled the g4 series special case in stm.py... if anyone has suggestions for a better ~hack~ fix then I'm all ears.

**Comment by salkinium** [comment]
We could remove 32kb programmatically for all G4s inside device tree file, then the patch and the hack would not be required?

**Comment by salkinium** [comment]
Oh, that does not work for all G4s, since CCM size varies. I would perhaps still fix the 91/A1 RAM sizes in code rather than the files to make it futureproof.

**Comment by twast92** [comment]
So keep the fix as it is?

**Review by salkinium — APPROVED** [review]

**Comment by salkinium** [comment]
(You need to open a PR in modm to update the modm-devices submodule sha to make this change go into effect.)

**Pull request merged**
