### PR TITLE
Fix size of SRAM2 of L431, L433, L443, L496 and L4A6

### LINKED ISSUE #33: STM32L431 RAM configuration is wrong
This MCU has a total RAM of 64kB, divided into 48kB SRAM1 and 16kB SRAM2. modm configures both of a size of 32kB. Not sure where the error comes from, looking at similar MCU their configuration is fine. Neither I have an idea how to fix that. So I'd ask for help. :-)

Not sure if it would be part of modm-devices as well, maybe the linker script could be updated to include SRAM2 section as well? Switching the MCU to a power savings mode retains SRAM2 only.

### PR DESCRIPTION
**Pull request by mikewolfram**
Fixes #33.

### CODE REVIEW

**Comment by mikewolfram** [comment]
Maybe you could tell me what exactly failed?

**Comment by salkinium** [comment]
> Maybe you could tell me what exactly failed?

Connection timeout in downloading CubeMX… Not your fault.

**Comment by salkinium** [comment]
> Maybe you could tell me what exactly failed?

Ah, so you need to commit the changed files too, because the CI only checks if things changed, it does not automatically add new changes. Preferrably do it as a separate commit, so you don't have to scroll forever to get to the code changes.

The CI could theoretically add the changes, however, I'm uncomfortable to let it run wild without a human in-the-loop at least for viability testing. (I know this repo is lacking actual coded consistency tests, it's on my ToDo list).

**Comment by mikewolfram** [comment]
I should stop working 14+ hours a day. Thought I committed the two XML files as well, but were running "git add ." in the wrong directory.

**Comment by salkinium** [comment]
Ok, so you need to update the git submodule in modm to this new commit in order to use this data.
Beware that this may break unrelated code, due to other changes that accumulated!

**Pull request merged**
