### PR TITLE
Update H5/H7/U5 support.

### LINKED ISSUE #102: STM32U595/5A5/599/5A9 not being generated
It looks like stm.py was set up to ignore STM32U59 and STM32U5A prefixes at some point.  We are considering using one of these due to their larger 4M flash sizes and I wanted to view their pinouts in my stm_layout_tk tool, so I updated modm-devices on my system but was surprised to see these ones missing.  I eventually found where they were being ignored and removed those lines, but then it errors out about missing memory models for the 599/5A9 series so I put those back on ignore.  I also noticed that these are listed as 85C parts and there wasn't an 85C entry in the temperature map.

This is my diff so far:
```
diff --git a/tools/generator/dfg/stm32/stm.py b/tools/generator/dfg/stm32/stm.py
index 362a04a..00ffb4c 100644
--- a/tools/generator/dfg/stm32/stm.py
+++ b/tools/generator/dfg/stm32/stm.py
@@ -8,8 +8,8 @@ LOGGER = logging.getLogger("dfg.stm.data")

 ignored_devices = \
 [
-    "STM32U59",
-    "STM32U5A",
+    "STM32U599",
+    "STM32U5A9",
     "STM32WL5M",
     "STM32WB1M",
     "STM32WB5M",
diff --git a/tools/generator/dfg/stm32/stm_device_tree.py b/tools/generator/dfg/stm32/stm_device_tree.py
index 7896252..2190680 100644
--- a/tools/generator/dfg/stm32/stm_device_tree.py
+++ b/tools/generator/dfg/stm32/stm_device_tree.py
@@ -26,7 +26,7 @@ class STMDeviceTree:
     """
     rootpath = os.path.join(os.path.dirname(__file__), "..", "..", "raw-device-data", "stm32-devices", "mcu")
     familyFile = XMLReader(os.path.join(rootpath, "families.xml"))
-    TemperatureMap = {0: "6", 105: "7", 125: "3"}
+    TemperatureMap = {0: "6", 85: "6", 105: "7", 125: "3"}

     @staticmethod
     def _format_raw_devices(rawDevices):
```

I'm not sure why those MCUs were originally put on ignore, so maybe there's some other reason to blacklist them?  I can also try and sort out the missing memory models if you like.

### PR DESCRIPTION
**Pull request by tgree**
This updates support for the previously-ignored U599/U5A9 (fixes #102).  It also adds <Frequency> tags to the stm32 patch for many H5/H7 devices as well as updating the memory models for some H5 devices.

### CODE REVIEW

**Comment by tgree** [comment]
It looks like there is an issue trying to test pushing to pypi.org.  They have changed their authentication process recently so you may have to sort something out on your end for that to pass.  It would be really nice if the pypi.org package could be updated with the newer device support since it doesn't look to have been sync'd for over a year.

**Comment by rleh** [comment]
I think the only problem with the pypi package is, that our version number has not been increased since over a year: https://github.com/modm-io/modm-devices/blob/cd25d127216a27390a86eaddbc002a454b3f6997/modm_devices/__init__.py#L19

**Review by rleh — APPROVED** [review]
Thanks!

**Comment by tgree** [comment]
> I think the only problem with the pypi package is, that our version number has not been increased since over a year:
> 
> https://github.com/modm-io/modm-devices/blob/cd25d127216a27390a86eaddbc002a454b3f6997/modm_devices/__init__.py#L19

Oh, it's weird there was a red "X" on the last commit but now it is a green checkmark.  When I clicked on the red "X" yesterday, it looked like it had errored out trying to do some test against pypi.org.  Did you want me to change the version number in this PR as well?

**Review by salkinium — APPROVED** [review]
Thanks a lot for fixing and updating this!

> Did you want me to change the version number in this PR as well?

No, I'll tag it later myself.

**Pull request merged**
